In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv(r'C:\Data Analitic\Python\Новая папка\survey_results_public.csv',low_memory=False)
df1 = pd.read_csv(r'C:\Data Analitic\Python\Новая папка\survey_results_schema.csv',low_memory=False)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

In [32]:
df.head(3)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0

In [33]:
df1.head(3)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0

Завдання 1. Підрахунок загальної кількості респондентів

In [34]:
df['ResponseId'].nunique()

49191

Завдання 2. Аналіз повноти відповідей респондентів

In [35]:
questions = set(df1['qname'])

questions_in_df = list(questions.intersection(set(df.columns)))

df_filtered = df[questions_in_df]

df_complete = df_filtered.dropna()

df_complete.shape[0]

0

Завдання 3. Статистичний аналіз досвіду респондентів

In [36]:
print('Міри центральної тенденції :')

# прибираємо пропуски у колнці досвіду
work_exp = df['WorkExp'].dropna()

print(f"Mean: {round(work_exp.mean(), 1)}")

print(f"Median: {work_exp.median()}")

print(f"Mode: {work_exp.mode()[0]}")

Міри центральної тенденції :
Mean: 13.4
Median: 10.0
Mode: 10.0

Завдання 4. Аналіз віддаленої роботи

In [37]:
# фільтруємо тих хто працює віддалено
remote_workers = df[df['RemoteWork'] == 'Remote']

remote_workers.shape[0]

10931

Завдання 5. Визначення популярності Python

In [38]:
# Перевіряємо чи є Python
worked_with_python = df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)

# Рахуємо кількість
python_count = worked_with_python.sum()
total = df.shape[0]
percentage = (python_count / total) * 100

print(f"Відсоток респондентів: {round(percentage, 1)}%")

Відсоток респондентів: 37.5%

Завдання 6. Аналіз шляхів навчання програмуванню

In [42]:
# Перенвіряємо чи навчався через онлайн-курси
learned_online_courses = df['LearnCode'].str.contains('Online Courses or Certification', case=False, na=False)

# Рахуємо кількість
online_courses_count = learned_online_courses.sum()

print(online_courses_count)

10973

Завдання 7. Географічний аналіз компенсації Python-розробників

In [45]:
#  Вибираємо тих хто працює з Python
df_python = df[df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)]

#  Видаляємо рядки без ЗП
df_python = df_python.dropna(subset=['ConvertedCompYearly'])

#  Групуємо
result = df_python.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median', 'count']).reset_index()

# Прибираємо країни з малою вибіркою
result = result[result['count'] >= 50]
result = result.drop(columns=['count'])

# Сортуємо по медіані
result = result.sort_values(by='median', ascending=False)

# Топ 10 країн по медіані компенсації
result.head(10)

,Country,mean,median
145,United States of America,173298.590211,150000.0
65,Israel,135828.365385,142594.0
132,Switzerland,156456.600000,142592.0
63,Ireland,120523.918919,116015.0
38,Denmark,115672.425000,98289.0
7,Australia,118091.410423,97514.0
143,United Kingdom of Great Britain and Northern I...,117662.362667,94958.5
101,Norway,104690.125000,89439.0
26,Canada,102846.026423,87550.0
48,Germany,86362.623737,81210.0

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [41]:
df_selected = df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]
df_clean = df_selected.dropna(subset=['ConvertedCompYearly'])

# Сортуємо за зарплатою 
df_sorted = df_clean.sort_values(by='ConvertedCompYearly', ascending=False).reset_index(drop=True)

# Беремо топ-5
top_5 = df_sorted.head(5)

top_5[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0